/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
    export interface GlobalComponents {
        AAnchor: typeof import('@arco-design/web-vue')['Anchor']
        AAnchorLink: typeof import('@arco-design/web-vue')['AnchorLink']
        AButton: typeof import('@arco-design/web-vue')['Button']
        ACheckbox: typeof import('@arco-design/web-vue')['Checkbox']
        ACol: typeof import('@arco-design/web-vue')['Col']
        ACollapse: typeof import('@arco-design/web-vue')['Collapse']
        ACollapseItem: typeof import('@arco-design/web-vue')['CollapseItem']
        ADoption: typeof import('@arco-design/web-vue')['Doption']
        ADropdown: typeof import('@arco-design/web-vue')['Dropdown']
        AForm: typeof import('@arco-design/web-vue')['Form']
        AFormItem: typeof import('@arco-design/web-vue')['FormItem']
        AGrid: typeof import('@arco-design/web-vue')['Grid']
        AGridItem: typeof import('@arco-design/web-vue')['GridItem']
        AInput: typeof import('@arco-design/web-vue')['Input']
        AInputNumber: typeof import('@arco-design/web-vue')['InputNumber']
        AInputSearch: typeof import('@arco-design/web-vue')['InputSearch']
        ALayout: typeof import('@arco-design/web-vue')['Layout']
        ALayoutContent: typeof import('@arco-design/web-vue')['LayoutContent']
        ALayoutHeader: typeof import('@arco-design/web-vue')['LayoutHeader']
        ALayoutSider: typeof import('@arco-design/web-vue')['LayoutSider']
        ARadio: typeof import('@arco-design/web-vue')['Radio']
        ARadioGroup: typeof import('@arco-design/web-vue')['RadioGroup']
        ARow: typeof import('@arco-design/web-vue')['Row']
        ASlider: typeof import('@arco-design/web-vue')['Slider']
        ASpace: typeof import('@arco-design/web-vue')['Space']
        ATag: typeof import('@arco-design/web-vue')['Tag']
        Card: typeof import('./src/components/Card.vue')['default']
        RouterLink: typeof import('vue-router')['RouterLink']
        RouterView: typeof import('vue-router')['RouterView']
    }
}
